---
title: "5.2 Data Stewardship"
---

+:------------------------------:+
| ### Safety First               |
+--------------------------------+

> As you learned in the data privacy submodule, the United States' data security laws are evolving and have gaps to address. This module explores how the European Union regulates data privacy and prescribes practices for responsible stewardship of data that is collected and processed by entities within its jurisdiction.

## Read

1.  Wolford, B. (n.d.) [What is GDPR, the EU's new data protection law?](https://gdpr.eu/what-is-gdpr/)

2.  Klosowski, T. [The State of Consumer Data Privacy Laws in the US (And Why It Matters)](https://www.nytimes.com/wirecutter/blog/state-of-privacy-laws-in-us/), 2021

## Post

Address the following:

1.  Describe two differences between US and EU data privacy laws. What are the implications of these differences for safeguarding your personal information?

2.  As we've learned this semester, your personal data can be used by different entities for economic gain as well as improvements to how we live, work, and play. If you could choose how your data are used, what would you permit versus prohibit and why?

Discussion posts are the primary assessment of your understanding and critical assessment of readings. You must reference the readings analyzed in your posts using in-text APA style. Posts should range between 400-500 words.

**Due by:** 11/16 11:59 pm EST
