---
title: "5.1 Data Privacy"
---

+:-----------------------:+
| ### The Privacy Paradox |
+-------------------------+

> Although a majority of people claim that privacy is important to them, few take steps to protect it online or through devices that sense location, voice, images, and other identifiable features. This module explores the reasons for this paradox and what actions policy-makers (and you) can take to protect the big data that you generate.

## Read and Listen

1.  Hot off the press this month from the Pew Research Center. . .

    1.  First, [take this quiz to test your knowledge of digital topics](https://www.pewresearch.org/internet/quiz/digital-knowledge-quiz-2023/) relative to a nationally representative survey of 5,101 randomly selected U.S. adults in May 2023.

    2.  Next, read the report titled "How Americans View Data Privacy" by Colleen McClain, Michelle Faverio, Monica Anderson and Eugenie Parkand (October 2023). \*\***Read** **p. 1-12 and take a deeper dive into a set of responses that interest you.\*\***

2.  WNYC Note to Self, [Privacy Paradox](https://project.wnyc.org/privacy-paradox/), 2017. Listen to **at least one of the Day 1-5 Challenges AND complete the challenge it poses at the end**. All five are interesting and worth your time. [See this list of the actions](https://www.wnyc.org/story/privacy-paradox-tip-sheet/) discussed in the podcasts that you can take to protect your data privacy.

3.  Ted Radio Hour, [Edward Snowden: Why does online privacy matter?](https://www.npr.org/transcripts/818341273), 2020. 

4.  Congressional Research Service, "[Overview of the American Data Privacy and Protection Act (ADPPA), H.R. 8152](https://crsreports.congress.gov/product/pdf/LSB/LSB10776)," 2022.

## Post

Address the following in the [5.1 Data Privacy](/discussions/M5-1.qmd) discussion board:

-   one statistic from the Pew survey that you feel is most urgent to address by policy-makers. Why?

-   Describe which Privacy Paradox Challenge that you chose, what information surprised you from the podcast, and what you learned from completing the challenge at the end.

-   The *proposed* American Data Privacy and Protection Act (ADPPA) from 2022 is the most recent action that Congress has taken to protect your data privacy. Describe one of the facets of the bill that you think will address the statistic you cited from the Pew survey and how it will work. Also discuss how it may fall short.

Discussion posts are the primary assessment of your understanding and critical assessment of readings. You must reference the readings analyzed in your posts using in-text APA style. Posts should range between 400-500 words.

**Due by:** 11/5 11:59 pm EST

## Respond

This week you are assigned to small groups for the last time this semester to learn what content your peers explored and their thoughts on data privacy. Read two of your group members' posts and describe how your viewpoints converge and diverge. Please make sure that everyone in your group gets at least one set of comments.

**Due by:** 11/9 at 11:59 pm EST
