---
title: "1.1 The Value of Big Data"
editor: visual
---



This module introduces you to the opportunities and challenges of big data for the public sector. You'll learn the characteristics that define big data and begin to think about how to apply it to your own field of study.

## Transforming Information to Ideas

This week we'll explore the characteristics of big data and its value to the public sector.

## Read

1.  Desouza & Smith, [Big Data for Social Innovation](https://gastate.view.usg.edu/content/enforced2/2797662-UR_csearcy_07/Files_Module%201/Desouza_Smith_Big_Data_for_Social_Innovation.pdf?_&d2lSessionVal=tsNzx3Ovvtpcdu9pGb63DMVZg&ou=2797662), *Stanford Social Innovation Review*, Summer 2014.

2.  World Bank Group, [Big Data in Action for Government](https://gastate.view.usg.edu/content/enforced2/2797662-UR_csearcy_07/Files_Module%201/World_Bank_WGSBigDataGovernmentFinal.pdf?_&d2lSessionVal=tsNzx3Ovvtpcdu9pGb63DMVZg&ou=2797662), World Bank Governance Practice, 2017.

3.  Meier, P., [Digital Humanitarians, Chapter 1](https://gastate.view.usg.edu/content/enforced2/2797662-UR_csearcy_07/Files_Module%201/Meier_Ch1.pdf?_&d2lSessionVal=tsNzx3Ovvtpcdu9pGb63DMVZg&ou=2797662), CRC Press, 2015.

4.  Pentland, A. [Social Physics, Chapter 1](https://gastate.view.usg.edu/content/enforced2/2797662-UR_csearcy_07/Files_Module%201/Pentland_Ch1.pdf?_&d2lSessionVal=tsNzx3Ovvtpcdu9pGb63DMVZg&ou=2797662), Penguin Group, 2015.

## Prepare

Please prepare to discuss your thoughts on the following prompts:

1.  Describe two characteristics of big data and how they apply to data produced or are used by your field of interest.

2.  Describe ideas or practices in this week's readings that you had not considered before.

3.  What claims about social physics do you find valid? In what ways would you challenge Pentland's "promise" of social physics?

## Attend

In person discussion, 1/17 at 4:30-5:30pm

