---
title: "2.2 Eyes in the Skies & Remote Sensing"
---

+:-------------------------:+
| ### Eyes and Ears of Data |
+---------------------------+

> Image and video data from satellites, drones, traffic lights, door bells, body cameras, and of course, your own phones are changing how we identify and respond to public problems. This week's module exposes you to the diversity of these data and some of their processing challenges.

## Read

1.  McKinsey Global Institute. "[Smart Cities: Digital Solutions for a More Livable Future.](https://gastate.view.usg.edu/content/enforced2/2885410-CO.090.EC.ECON8000.XLS.PZ11.20242/Files_Module%202/mgi-smart-cities-full-report.pdf?isCourseFile=true&ou=2885410)" 2018. **\*\*Read the executive summary only (unless you want to read more!\*\*)**

2.  [Humanitarian OpenStreetMap Team](https://www.hotosm.org/), What We Do and Our Work. n.d. **\*\*Browse site for applications to your field of interest.\*\***

3.  Future of Privacy Forum, ["Understanding Facial Detection, Characterization, and Recognition Technologies](https://gastate.view.usg.edu/content/enforced2/2885410-CO.090.EC.ECON8000.XLS.PZ11.20242/Files_Module%202/FPF_FaceRecognitionPoster_R5.pdf?isCourseFile=true&ou=2885410)," 2018.

## Post

Address the following in [Discussion 3](/discussions/M2-2.qmd)：

1.  The readings from the last two submodules (2.1 and 2.2) describe use cases for social data, surveillance systems, satellite and aerial imagery, and other types of sensing data (e.g., biometric, IOT, etc.). Describe what promise these types of data hold for the public sector in your interest areas. What concerns do you have about the use of these data for the purposes you describe or otherwise?

2.  Revisit the research question that you're exploring for your big data project proposal. Describe types of data from the last two submodules (2.1 and 2.2) that you hadn't considered before but could incorporate into your proposal. Describe how they might improve your project and their limitations.

Discussion posts are the primary assessment of your understanding and critical assessment of readings. You must reference the readings you describe using in-text using APA style. Posts should range between 400-500 words.

**Due by:** 9/24 11:59 pm EST
