---
title: "Course Completion Checklist"
---

+:---------------------------------:+
| ### Great Job this Semester       |
+-----------------------------------+

> I've enjoyed getting to know you this semester and encourage you to stay in touch as you finish your graduate degrees. Feel free to contact me about topics in this course or if you just want to talk about your career.

## Data Certifications

At the beginning of the semester you submitted a plan to complete five workshops to advance your data knowledge and skills. To complete this requirement for the course:

-   Write a short report after each data workshop by describing:

    1.  What you learned (in your own words, not the workshop description);\
    2.  How you'll use the new skills in your project proposal (or elsewhere); and,\
    3.  Whether you recommend the workshop to other students.

    **Submit an example of work that you generated in the training**. You can embed it in your reflection or attach it separately.

    Label each report with the workshop title, link, and date completed.

-   Submit each report to its separate assignment folder. **All data workshop reflections are due by 12/3 at 11:59 pm**.

-   Don't forget to add your data certifications to your resume and/or LinkedIn profile!

## Big Data Project Proposal

-   Early in the semester you identified a research question and examined existing literature on the topic of your big data project proposal, so you should have a good start on this final deliverable for the class. As you complete your proposal, [review the instructions](https://gastate.view.usg.edu/content/enforced2/2885410-CO.090.EC.ECON8000.XLS.PZ11.20242/Files_Module%203/Big%20Data%20Project%20Proposal%20Instructions.docx?ou=2885410) to make sure you include requested information in each section and follow formatting guidelines. You also can view these sample proposals from prior students in this course:

    -   Sample 1

    -   Sample 2

-   As you complete your proposal, use Grammarly to check for poor writing, spelling, and plagiarism.

-   Submit the proposal to the [Big Data Project Proposal](/assignments/project_proposal.qmd) assignment folder by **12/10 11:59pm**. \*\*This is a slightly later date than the syllabus.\*\*

-   It may take a few minutes after you upload your paper, but you will have access to a [Similarity Report](https://help.turnitin.com/feedback-studio/d2l/student/the-similarity-report/interpreting-the-similarity-report.htm) that checks for plagiarism in your paper. You can [access the Similarity Report using these instructions](https://help.turnitin.com/feedback-studio/d2l/student/the-similarity-report/accessing-the-similarity-report.htm). If you need to make changes to your paper, do so and upload it again to the same assignment folder.

**Have a wonderful winter break!**
