project:
  type: website
  output-dir: docs

website:
  title: "Big Data for Public Good"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - href: modules/module1.qmd
        text: Modules


format:
  html:
    theme: united
    css: html/styles.css
    toc: true



