project:
  type: website
  output-dir: docs

website:
  title: "Big Data for Public Good"
  bread-crumbs: false
  navbar:
    search: true
    left:
     - href: syllabus.qmd
       text: Syllabus
       
     - text: Modules
       menu: 
        - text: Module 1 - Introduction to Big Data
          file: modules/module1-0.qmd
        - text: Module 2 - Types of Big Data
          file: modules/module2-0.qmd
        - text: Module 3 - Discovery & Insights
          file: modules/module3-0.qmd
        - text: Module 4 - Bias in Big Data
          file: modules/module4-0.qmd
        - text: Module 5 - Data Privacy & Stewardship
          file: modules/module5-0.qmd
        - text: Module 6 - Course Conclusion
          file: modules/module6-0.qmd         

     - text: Assignments
       menu: 
        - text: Discussions
          file: discussions/module1.qmd
        - text: Labs
          file: assignments/lab1.qmd
        - text: Data Certification
          file: assignments/data-certification-plan.qmd
        - text: Big Data Project Proposal
          file: assignments/project_proposal.qmd

     - text: Resources
       menu: 
        - text: Rubrics
          file: resources/rubrics-written.qmd
        - text: Grade and Policies
          file: resources/grade-policy.qmd 
          
     - text: About
       file: about.qmd
    tools:
     - icon: github
       href: https://github.com/yemeng-emma/bigdata4publicgood
       aria-label: github
      
  sidebar:
     - title: "Modules"
       style: "docked"
       search: false
       background: dark
       contents:
         - section: "Module 1 - Introduction to Big Data"
           contents: 
            - text: "Module Overview"
              file: modules/module1-0.qmd
            - text: "1.1  The Value of Big Data"
              file: modules/module1-1.qmd
            - text: "1.2 Big Data and You"
              file: modules/module1-2.qmd
            - text: "1.3 The Challenges of Big Data"
              file: modules/module1-3.qmd            
         - section: "Module 2 - Types of big data"
           contents: 
            - text: "Module Overview"
              file: modules/module2-0.qmd
            - text: "2.1"
              file: modules/module2-1.qmd
            - text: "2.2"
              file: modules/module2-2.qmd
            - text: "2.3"
              file: modules/module2-3.qmd            


     - title: "Discussions"
       style: "docked"
       background: light
       contents:
         - discussions/overview.qmd
         - discussions/module1.qmd
         - discussions/module2.qmd
         - discussions/module3.qmd
         - discussions/module4.qmd
         - discussions/module5.qmd
         - discussions/module6.qmd


     - title: "Rubrics"
       style: "docked"
       background: light
       contents:
         - resources/rubrics-written.qmd
         - resources/rubrics-discussion.qmd



     - title: "Labs"
       style: "docked"
       background: light
       contents:
         - assignments/lab1.qmd
         - assignments/lab2.qmd
         - assignments/lab3.qmd
         - assignments/lab4.qmd
         - assignments/lab5.qmd
         - assignments/lab6.qmd
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true



