---
title: "Written Assignment Rubrics"
editor: visual
---

Rubric Name: Grading Rubric_Written Assignment

+:-------------------------------------------+:---------------------------------------------------------------------------------------------------------------------------+:-------------------------------------------------------------------------------------------------------------+:-----------------------------------------------------------------------------------------------------------------------------+:------------------------------------------------------------------------------------------------------+
| Criteria                                   | **Advanced**                                                                                                               | **Proficient**                                                                                               | **Developing**                                                                                                               | **Insufficient**                                                                                      |
+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| Assignment Specific Grading Items          | 40 points                                                                                                                  | 35 points                                                                                                    | 30 points                                                                                                                    | 20 points                                                                                             |
|                                            |                                                                                                                            |                                                                                                              |                                                                                                                              |                                                                                                       |
|                                            | Assignment instructions are followed.                                                                                      | Assignment instructions are mostly followed.                                                                 | Assignment instructions largely are not followed or don't address many requirements.                                         | Assignment instructions are not followed or attempts are largely inaccurate.                          |
|                                            |                                                                                                                            |                                                                                                              |                                                                                                                              |                                                                                                       |
|                                            | Required items and formatting are addressed comprehensively and accurately.                                                | Required items and formatting are addressed accurately.                                                      |                                                                                                                              |                                                                                                       |
+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| Critical Analysis (Understanding of Topic) | 40 points                                                                                                                  | 35 points                                                                                                    | 30 points                                                                                                                    | 20 points                                                                                             |
|                                            |                                                                                                                            |                                                                                                              |                                                                                                                              |                                                                                                       |
|                                            | Content displays excellent comprehension, application, and/or analysis of the topic and underlying concepts.               | Content presents basic comprehension, application, and/or analysis of the topic and underlying concepts.     | Content presents little to no comprehension, application, and/or analysis of the topic and underlying concepts.              | Content presents no comprehension, application, and/or analysis of the topic and underlying concepts. |
|                                            |                                                                                                                            |                                                                                                              |                                                                                                                              |                                                                                                       |
|                                            | Includes correct use of terminology.                                                                                       | Includes correct use of terminology.                                                                         | Includes incorrect use of terminology.                                                                                       | Integrates no relevant evidence to support important points.                                          |
+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| Writing & Clarity                          | 20 points                                                                                                                  | 15 points                                                                                                    | 10 points                                                                                                                    | 5 points                                                                                              |
|                                            |                                                                                                                            |                                                                                                              |                                                                                                                              |                                                                                                       |
|                                            | Writing is clear, well-written and free of grammatical and spelling mistakes. Required citations are included and correct. | Writing is clear, with a few grammatical and spelling mistakes. Required citations are included and correct. | Writing is clear but there are many spelling and grammatical mistakes. Required citations are incorrect or some are missing. | Writing is unclear or diff                                                                            |
+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
