---
title: "Discussion Posts Rubrics"
editor: visual
---

+:-------------------------------------------+:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+:-----------------------------------------------------+
| Criteria                                   | **Advanced**                                                                                                                                                                                                                                                                                     | **Proficient**                                                                                                                                                                               | **Developing**                                                                                                                                                                                                                                                                                                  | **Emerging**                                                                                                                                                                                                                | **Criterion Score**                                  |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+
| Assignment Specific Grading Items          | 5 points                                                                                                                                                                                                                                                                                         | 4 points                                                                                                                                                                                     | 3 points                                                                                                                                                                                                                                                                                                        | 2 points                                                                                                                                                                                                                    | Score of Assignment Specific Grading Items,          |
|                                            |                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                             |                                                      |
|                                            | Assignment questions and required items are addressed comprehensively, accurately and specifically. Offers strong support for arguments or points.                                                                                                                                               | Most questions and requirements are addressed accurately and specifically. Support for arguments or points may be weak.                                                                      | Missing answers to questions or doesn\'t address many requirements. Support for arguments or points is weak.                                                                                                                                                                                                    | Does not address questions or requirements, or attempts are largely inaccurate.                                                                                                                                             | / 5                                                  |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+
| Critical Analysis (Understanding of Topic) | 10 points                                                                                                                                                                                                                                                                                        | 8 points                                                                                                                                                                                     | 6 points                                                                                                                                                                                                                                                                                                        | 4 points                                                                                                                                                                                                                    | Score of Critical Analysis (Understanding of Topic), |
|                                            |                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                             |                                                      |
|                                            | Writing displays an excellent understanding of the required readings and underlying concepts including correct use of terminology. Integrates lectures, readings, or relevant research, or specific real-life application (work experience, prior coursework, etc.) to support important points. | Writing repeats and summarizes basic, correct information, but does not apply enough lectures, readings, or relevant research or specific real-life applications                             | Writing shows little or no evidence that class lectures and readings were understood. Writings are largely personal opinions or feelings, or "I agree" or "Great idea," without supporting statements with concepts from the readings, outside resources, relevant research, or specific real-life application. | Writing lacks evidence of critical analysis, and poor use of supportive evidence.                                                                                                                                           | / 10                                                 |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+
| Writing & Clarity                          | 5 points                                                                                                                                                                                                                                                                                         | 4 points                                                                                                                                                                                     | 3 points                                                                                                                                                                                                                                                                                                        | 2 points                                                                                                                                                                                                                    | Score of Writing & Clarity,                          |
|                                            |                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                             |                                                      |
|                                            | Answers are clear, well-written and free of grammatical and spelling mistakes. No errors in APA style. Scholarly style. Cites all data obtained from other sources. APA citation style is used in both text and/or bibliography.                                                                 | Answers are clear, a few small grammatical and spelling mistakes. Rare errors in APA style that do not detract from the paper. Scholarly style. Cites most data obtained from other sources. | Answers are clear but there are many spelling and grammatical mistakes. Errors in APA style are noticeable. Cites some data obtained from other sources. Citation style is either inconsistent or incorrect.                                                                                                    | Answers are unclear or difficult to understand, and/or there are many spelling and grammatical mistakes. Errors in APA style detracts substantially from the paper. Word choice is informal in tone. Does not cite sources. | / 5                                                  |
+--------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+

Total Score of Grading Rubric_Discussion Posts, / 20
