---
title: "Discussion 3"
---

## M2.2 Eyes in the Skies

**Post**

Address the following:

1.  The readings from the last two submodules (2.1 and 2.2) describe use cases for social data, surveillance systems, satellite and aerial imagery, and other types of sensing data (e.g., biometric, IOT, etc.). Describe what promise these types of data hold for the public sector in your interest areas. What concerns do you have about the use of these data for the purposes you describe or otherwise?

2.  Revisit the research question that you're exploring for your big data project proposal. Describe types of data from the last two submodules (2.1 and 2.2) that you hadn't considered before but could incorporate into your proposal. Describe how they might improve your project and their limitations.

Discussion posts are the primary assessment of your understanding and critical assessment of readings. You must reference the readings analyzed in your posts using in-text APA style. Posts should range between 400-500 words. 

**Due by:** 9/24 11:59 pm EST

See here for [Rubrics](/resources/rubrics-discussion.qmd)
