---
title: "Discussion M4.1"
---

## M4.1 Data Quality

**Post**

Address the following:

-   Poor data quality and data practices can lead to downstream bias that impacts individuals and decision-making. What examples from the readings (or your own reading) do you consider most harmful? Overblown?

-   Governments around the world are developing frameworks for improving data integrity and reducing bias. Based on your own experience as a user and/or analyst of data, what elements of the framework do you think are least understood or practiced by researchers/government agencies? How might they improve?

-   Find an example of a recent data quality problem in the news that resulted in bias from big data. What was the origin of the bias and did the media address how to prevent it? Describe what you find surprising about the problem. (Make sure to cite the article.)

Discussion posts are the primary assessment of your understanding and critical assessment of readings. You must reference the readings analyzed in your posts using in-text APA style. Posts should range between 400-500 words. 

**Due by:** 10/15 11:59 pm EST
