---
title: "Discussion 7"
---

## M5.2 Data Privacy

## Post

Address the following:

-   Describe one statistic from the Pew survey that you feel is most urgent to address by policy-makers. Why?

-   Describe which Privacy Paradox Challenge that you chose, what information surprised you from the podcast, and what you learned from completing the challenge at the end.

-   The *proposed* American Data Privacy and Protection Act (ADPPA) from 2022 is the most recent action that Congress has taken to protect your data privacy. Describe one of the facets of the bill that you think will address the statistic you cited from the Pew survey and how it will work. Also discuss how it may fall short.

Discussion posts are the primary assessment of your understanding and critical assessment of readings. You must reference the readings analyzed in your posts using in-text APA style. Posts should range between 400-500 words.

**Due by:** 11/5 11:59 pm EST

## Respond

This week you are assigned to small groups for the last time this semester to learn what content your peers explored and their thoughts on data privacy. Read two of your group members' posts and describe how your viewpoints converge and diverge. Please make sure that everyone in your group gets at least one set of comments.

**Due by:** 11/9 at 11:59 pm EST

See here for [Rubrics](/resources/rubrics-discussion.qmd)
