---
title: Module 1 Discussions
---

## M1.2 The Value of Big Data

**Post**

Address the following:

1.  Describe two characteristics of big data and how they apply to data produced or used by your field of interest.

2.  Describe ideas presented in two of this week's readings that you had not considered before.

3.  What questions do you have about big data that we can address this week in class?

Due by: 8/29 11:59 pm EST

**Discuss**

Online discussions are important to the dialogue and learning in this class. Take some time to respond to at least two of your classmates' posts by Friday.

Due by: 9/3 11:59 pm EST


## M1.4 The Value of Big Data

**Post**

Address the following:

1.  Describe two characteristics of big data and how they apply to data produced or used by your field of interest.

2.  Describe ideas presented in two of this week's readings that you had not considered before.

3.  What questions do you have about big data that we can address this week in class?

Due by: 8/29 11:59 pm EST

**Discuss**

Online discussions are important to the dialogue and learning in this class. Take some time to respond to at least two of your classmates' posts by Friday.

Due by: 9/3 11:59 pm EST
